"""
Phase 3 — Prometheus Metrics Exporter.

Extends the Phase 1 LLMMetricsCollector with Prometheus-native counters,
histograms, and gauges for Grafana dashboard consumption.

Exposes a /metrics endpoint via prometheus_client.
"""
import logging
from typing import Optional

logger = logging.getLogger(__name__)

try:
    from prometheus_client import Counter, Histogram, Gauge, Info, CollectorRegistry, generate_latest
    PROMETHEUS_AVAILABLE = True
except ImportError:
    PROMETHEUS_AVAILABLE = False
    logger.warning("prometheus_client not installed. Prometheus metrics disabled.")


# ── Prometheus Metric Definitions ──────────────────────────────────────────

if PROMETHEUS_AVAILABLE:
    REGISTRY = CollectorRegistry()

    # API Layer
    API_REQUEST_COUNT = Counter(
        "electricai_api_requests_total",
        "Total API requests by method and endpoint",
        ["method", "endpoint", "status_code"],
        registry=REGISTRY
    )
    API_REQUEST_LATENCY = Histogram(
        "electricai_api_request_duration_seconds",
        "API request latency in seconds",
        ["method", "endpoint"],
        buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0],
        registry=REGISTRY
    )

    # AI Inference Layer
    AI_INFERENCE_COUNT = Counter(
        "electricai_ai_inference_total",
        "Total AI inference requests by provider and model",
        ["provider", "model", "task", "status"],
        registry=REGISTRY
    )
    AI_INFERENCE_LATENCY = Histogram(
        "electricai_ai_inference_duration_seconds",
        "AI inference latency in seconds",
        ["provider", "model"],
        buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0],
        registry=REGISTRY
    )
    AI_TOKENS_GENERATED = Counter(
        "electricai_ai_tokens_generated_total",
        "Total tokens generated by provider",
        ["provider"],
        registry=REGISTRY
    )
    AI_FALLBACK_COUNT = Counter(
        "electricai_ai_fallback_total",
        "Total deterministic fallback activations",
        ["task", "reason"],
        registry=REGISTRY
    )
    AI_CACHE_HIT_COUNT = Counter(
        "electricai_ai_cache_hits_total",
        "Semantic cache hits",
        registry=REGISTRY
    )
    AI_CACHE_MISS_COUNT = Counter(
        "electricai_ai_cache_misses_total",
        "Semantic cache misses",
        registry=REGISTRY
    )
    AI_VALIDATION_PASS = Counter(
        "electricai_ai_validation_pass_total",
        "7-point validator pass count",
        registry=REGISTRY
    )
    AI_VALIDATION_FAIL = Counter(
        "electricai_ai_validation_fail_total",
        "7-point validator fail count by audit point",
        ["audit_point"],
        registry=REGISTRY
    )

    # System Health
    ACTIVE_CONNECTIONS = Gauge(
        "electricai_active_connections",
        "Current active HTTP connections",
        registry=REGISTRY
    )
    GPU_UTILIZATION = Gauge(
        "electricai_gpu_utilization_percent",
        "GPU utilization percentage",
        ["gpu_id"],
        registry=REGISTRY
    )

    # Business Metrics
    BILLS_PROCESSED = Counter(
        "electricai_bills_processed_total",
        "Total bills processed",
        ["status"],
        registry=REGISTRY
    )

    # Build Info
    BUILD_INFO = Info(
        "electricai_build",
        "Build and version information",
        registry=REGISTRY
    )
    BUILD_INFO.info({
        "version": "3.0.0",
        "phase": "3",
        "component": "enterprise-platform"
    })


def get_metrics() -> bytes:
    """Generate Prometheus metrics output for /metrics endpoint."""
    if PROMETHEUS_AVAILABLE:
        return generate_latest(REGISTRY)
    return b"# Prometheus client not installed\n"


def record_api_request(method: str, endpoint: str, status_code: int, duration_seconds: float):
    """Record an API request metric."""
    if PROMETHEUS_AVAILABLE:
        API_REQUEST_COUNT.labels(method=method, endpoint=endpoint, status_code=str(status_code)).inc()
        API_REQUEST_LATENCY.labels(method=method, endpoint=endpoint).observe(duration_seconds)


def record_ai_inference(provider: str, model: str, task: str, status: str, duration_seconds: float, tokens: int = 0):
    """Record an AI inference metric."""
    if PROMETHEUS_AVAILABLE:
        AI_INFERENCE_COUNT.labels(provider=provider, model=model, task=task, status=status).inc()
        AI_INFERENCE_LATENCY.labels(provider=provider, model=model).observe(duration_seconds)
        if tokens > 0:
            AI_TOKENS_GENERATED.labels(provider=provider).inc(tokens)


def record_ai_fallback(task: str, reason: str):
    """Record a deterministic fallback activation."""
    if PROMETHEUS_AVAILABLE:
        AI_FALLBACK_COUNT.labels(task=task, reason=reason).inc()


def record_cache_hit():
    if PROMETHEUS_AVAILABLE:
        AI_CACHE_HIT_COUNT.inc()


def record_cache_miss():
    if PROMETHEUS_AVAILABLE:
        AI_CACHE_MISS_COUNT.inc()


def record_validation_pass():
    if PROMETHEUS_AVAILABLE:
        AI_VALIDATION_PASS.inc()


def record_validation_fail(audit_point: str):
    if PROMETHEUS_AVAILABLE:
        AI_VALIDATION_FAIL.labels(audit_point=audit_point).inc()


def record_bill_processed(status: str):
    if PROMETHEUS_AVAILABLE:
        BILLS_PROCESSED.labels(status=status).inc()
