"""Phase 2 — HTML Report Renderer."""
import html
from typing import Dict, Any


class HTMLReportRenderer:
    """Renders bill analysis narrative into styled responsive HTML."""

    @staticmethod
    def render(narrative_text: str, context_data: Dict[str, Any]) -> str:
        bill = context_data.get("bill", context_data)
        total = bill.get("total_bill", 0.0)
        usage = bill.get("usage_kwh", 0.0)
        period = bill.get("billing_period", "Current Period")

        # Convert markdown-style headings to HTML
        lines = narrative_text.split("\n")
        body_parts = []
        for line in lines:
            stripped = line.strip()
            if stripped.startswith("### "):
                body_parts.append(f"<h3>{html.escape(stripped[4:])}</h3>")
            elif stripped.startswith("## "):
                body_parts.append(f"<h2>{html.escape(stripped[3:])}</h2>")
            elif stripped.startswith("# "):
                body_parts.append(f"<h1>{html.escape(stripped[2:])}</h1>")
            elif stripped.startswith("- "):
                body_parts.append(f"<li>{html.escape(stripped[2:])}</li>")
            elif stripped == "---":
                body_parts.append("<hr>")
            elif stripped:
                body_parts.append(f"<p>{html.escape(stripped)}</p>")

        body_html = "\n".join(body_parts)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Electricity Bill Analysis Report</title>
    <style>
        body {{ font-family: 'Inter', -apple-system, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; color: #1a1a2e; background: #f8f9fa; }}
        h1 {{ color: #16213e; border-bottom: 3px solid #0f3460; padding-bottom: 0.5rem; }}
        h2 {{ color: #0f3460; margin-top: 1.5rem; }}
        h3 {{ color: #533483; margin-top: 1.2rem; }}
        .kpi-bar {{ display: flex; gap: 1.5rem; margin-bottom: 1.5rem; }}
        .kpi {{ background: white; border-radius: 8px; padding: 1rem 1.5rem; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }}
        .kpi-label {{ font-size: 0.75rem; text-transform: uppercase; color: #666; }}
        .kpi-value {{ font-size: 1.5rem; font-weight: 700; color: #0f3460; }}
        hr {{ border: none; border-top: 1px solid #dee2e6; margin: 1.5rem 0; }}
        p {{ line-height: 1.7; }}
        li {{ margin: 0.3rem 0; line-height: 1.6; }}
        .footer {{ margin-top: 2rem; font-size: 0.8rem; color: #999; text-align: center; }}
    </style>
</head>
<body>
    <h1>Electricity Bill Analysis Report</h1>
    <div class="kpi-bar">
        <div class="kpi"><div class="kpi-label">Billing Period</div><div class="kpi-value">{html.escape(str(period))}</div></div>
        <div class="kpi"><div class="kpi-label">Total Bill</div><div class="kpi-value">${total:.2f}</div></div>
        <div class="kpi"><div class="kpi-label">Usage</div><div class="kpi-value">{usage:.1f} kWh</div></div>
    </div>
    <hr>
    {body_html}
    <div class="footer">Generated by ElectricAI — Enterprise Bill Analytics Platform</div>
</body>
</html>"""
